---
# code: language=ansible

- name: 1Password CLI | Create folder /etc/debsig/policies/AC2D62742012EA22/
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/debsig/policies/AC2D62742012EA22
    - /usr/share/debsig/keyrings/AC2D62742012EA22

- name: 1Password CLI | Download policy and copy to /etc/debsig/policies/AC2D62742012EA22/
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol
    dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
    mode: "0644"

- name: 1Password CLI | Install repository keys
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: "{{ item }}"
    state: present
  loop:
    - /usr/share/keyrings/1password-archive-keyring.gpg
    - /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

- name: 1Password CLI | Configure apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ onepasswordcli_architecture }}
      signed-by=/usr/share/keyrings/1password-archive-keyring.gpg]
      https://downloads.1password.com/linux/debian/{{ onepasswordcli_architecture }}
      stable main
    filename: 1password.list
    state: present

- name: 1Password CLI | Install the 1password-cli package
  ansible.builtin.package:
    name: 1password-cli
