---
# code: language=ansible

- name: 1Password CLI | Install YUM RPM Key from https://downloads.1password.com/linux/keys/1password.asc
  ansible.builtin.rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc

- name: 1Password CLI | Configure the 1Password repository
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/\$basearch
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    file: 1password

- name: 1Password CLI | Install the 1password-cli package
  ansible.builtin.package:
    name: 1password-cli
    state: present
